kind: OpenLibertyApplication
apiVersion: apps.openliberty.io/v1
metadata:
  name: openliberty-system-microservice-cp4a-argo
  namespace: rlange
spec:
  applicationImage: quay.io/rslangehennig0/openliberty-system-microservice-cp4a:bfdac8f0
  expose: true
  manageTLS: true
  replicas: 3
  service:
    type: ClusterIP
    port: 9080
  serviceAccount:
    mountToken: true
