apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: openliberty-system-microservice-cp4a-argo
spec:
  applicationImage: quay.io/rslangehennig0/openliberty-system-microservice-cp4a:main
  service:
    type: ClusterIP
    port: 9080
  expose: true
